// Generated by ts-to-zod
import { z } from "zod";

export const VideoSchema = z.object({
  id: z.string(),
  created_at: z.string(),
  video_url: z.string().url(),
  description: z.string(),
  num_comments: z.number(),
  user_id: z.string(),
  title: z.string(),
});
